version: "3"
services:
  application:
    build: .
    image: gamja123/second-hand
    container_name: was-application
    ports:
      - 8080:8080
    expose:
      - 8080

  frontend:
    build: .
    container_name: frontend
    image: gamja123/frontend
    ports:
      - 3000:3000

  web:
    image: gamja123/second-hand-nginx
    container_name: was-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
      - application
