# .github/workflows/chromatic.yml

# Workflow name
name: "Chromatic Publish"

# Event for the workflow
on:
  push:
    branches: [dev-fe]
    paths: ["fe/src/components/**"]

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3

      - name: Change directory to 'fe'
        run: cd fe

      - name: Install dependencies
        run: npm install

      - name: Run Chromatic
        run: npm run chromatic

      - name: Publish to Chromatic
        #👇 Adds Chromatic as a step in the workflow
        uses: chromaui/action@v1
        with:
          #👇 Chromatic projectToken,
          token: ${{ secrets.GITHUB_TOKEN }}